### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by JaoNoctus** [JaoNoctus/voraz-skatepark#1]
- [x] Install **[Laravel 5.1](https://github.com/laravel/laravel/tree/5.1)**
- [x] Install **[Defender](https://github.com/artesaos/defender#installation)**
- [x] Install **[LaravelCollective/html 5.1](https://laravelcollective.com/docs/5.1/html#installation)**

**Comment by JaoNoctus** [comment]
- [x] **Laravel 5.1** `composer create-project laravel/laravel [folder] 5.1`

**Comment by JaoNoctus** [comment]
- [ ] Install **[Defender](https://github.com/artesaos/defender)**

**Comment by JaoNoctus** [comment]
- [ ] Install **[Admin LTE Laravel](https://github.com/acacha/adminlte-laravel#installation--use)**

**Comment by JaoNoctus** [comment]
Change the default language to **Portuguese - Brazil** _(pt-BR)_
